# Generated by Django 4.1.7 on 2023-03-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_no', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('profile_picture', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=250)),
                ('employee_id', models.IntegerField()),
            ],
            options={
                'db_table': 'employee_pictures',
            },
        ),
    ]
